# VERITAS: Copyright (c) 2022 Veritas Technologies LLC. All rights reserved.
#
# THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF VERITAS
# TECHNOLOGIES LLC.  USE, DISCLOSURE OR REPRODUCTION IS PROHIBITED WITHOUT THE
# PRIOR EXPRESS WRITTEN PERMISSION OF VERITAS TECHNOLOGIES LLC.
#
# The Licensed Software and Documentation are deemed to be commercial computer
# software as defined in FAR 12.212 and subject to restricted rights as defined
# in FAR Section 52.227-19 "Commercial Computer Software - Restricted Rights"
# and DFARS 227.7202, Rights in "Commercial Computer Software or Commercial
# Computer Software Documentation," as applicable, and any successor
# regulations, whether delivered by Veritas as on premises or hosted services.
# Any use, modification, reproduction release, performance, display or
# disclosure of the Licensed Software and Documentation by the U.S. Government
# shall be solely in accordance with the terms of this Agreement.
# Product version __version__

import os
import platform
import tempfile

import pytest

from use_core import appliance, utils, workload
from use_core.test.fixtures import (  # noqa: F401
    test_appliance_safety,
    test_appliances,
    test_appliances_with_non_5150,
)

try:
    import xlwings as xw
    from fixture_xl import (  # noqa: F401
        dwa_testcase,
        import_source_book,
        the_book,
        the_rep_nbdeployutil,
        the_rw_book_flex_minimal,
        the_rw_book_flexscale_multi,
        the_rw_book_master_skip,
        the_rw_book_multiple_failures,
    )
except ImportError:
    pass

if "RUN_STRESS" not in os.environ:
    collect_ignore = ["test_stress.py"]


@pytest.fixture(scope="session")
def excel_app():
    # hide the test app on macOS, but leave it alone on Windows.  This
    # minimizes disruption on both platforms by preventing Excel from
    # stealing focus
    plat = platform.system()
    app_visibility = plat != "Darwin"
    app = xw.App(visible=app_visibility)
    app.screen_updating = False
    yield app
    app.quit()


@pytest.fixture
def test_master_server():
    low_capacity_appliance = {
        "name": "5250 400GB_Capacity 0_Shelves 64_RAM  4x1GbE 2x10GbE_SFP",
        "model": "5250",
        "shelves": "0",
        "shelf_size": {"value": "65.5", "unit": "TB"},
        "capacity": {"value": "400", "unit": "GB"},
        "shelf_capacity": {"value": "0", "unit": "TB"},
        "calculated_capacity": {"value": "400", "unit": "GB"},
        "number_of_appliance_drives": "8",
        "drives_per_shelf": "12",
        "number_of_shelf_drives": "0",
        "number_of_total_drives": "8",
        "number_of_calculated_drives": "8",
        "drive_size": {"value": "2", "unit": "TB"},
        "memory": {"value": "64", "unit": "GB"},
        "io_config": "A",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "2", "io": "1600"},
        "twentyfive_gbe_sfp": {"count": "2", "io": "4000"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    return low_capacity_appliance


@pytest.fixture
def test_windows():
    w1 = {"Operation": "Incrementals", "Time (hours per week)": 24}
    w2 = {"Operation": "Full", "Time (hours per week)": 50}
    w3 = {"Operation": "Replications", "Time (hours per week)": 90}
    return [w1, w2, w3]


@pytest.fixture
def windows():
    return utils.WindowSize(
        full_backup_hours=60, incremental_backup_hours=24, replication_hours=90
    )


@pytest.fixture
def test_workloads():
    w1 = {
        "workload_name": "SAP",
        "workload_type": "Oracle",
        "number_of_clients": 10,
        "workload_size": utils.Size.assume_unit(10, "TB"),
        "storage_lifecycle_policy": "default",
        "workload_isolation": False,
        "universal_share": False,
        "domain": "Domain-1",
        "client_dedup": True,
        "region": "DC",
        "dr_dest": "SF",
        "backup_location_policy": "local+dr",
        "annual_growth_rate": 0.1,
        "daily_change_rate": 0.2,
        "incremental_retention_days": 30,
        "weekly_full_retention": 4,
        "monthly_retention": 6,
        "annually_retention": 0,
        "incremental_retention_dr": 30,
        "incremental_retention_cloud": 0,
        "weekly_full_retention_dr": 4,
        "weekly_full_retention_cloud": 0,
        "monthly_full_retention_dr": 6,
        "monthly_full_retention_cloud": 0,
        "annually_full_retention_dr": 0,
        "annually_full_retention_cloud": 0,
        "initial_dedup_rate": 0.55,
        "dedup_rate": 0.75,
        "incremental_backup_level": "differential",
        "log_backup_incremental_level": "differential",
        "log_backup_capable": True,
        "log_backup_frequency_minutes": 15,
        "appliance_front_end_network": appliance.NetworkType.auto,
        "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
        "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
        "force_small_dup_jobs": 30,
        "appliance_dr_network": appliance.NetworkType.auto,
        "appliance_ltr_network": appliance.NetworkType.auto,
        "files": 1,
        "channels": 1,
        "files_per_channel": 1,
        "dedupe_rate_adl_full": 0.85,
        "incremental_per_week": 5,
        "full_backup_per_week": 1,
    }
    w2 = {
        "workload_name": "New application",
        "workload_type": "VMware",
        "number_of_clients": 20,
        "workload_size": utils.Size.assume_unit(20, "TB"),
        "storage_lifecycle_policy": "default",
        "workload_isolation": False,
        "universal_share": False,
        "domain": "Domain-1",
        "client_dedup": False,
        "region": "DC",
        "dr_dest": "SF",
        "backup_location_policy": "local+dr",
        "annual_growth_rate": 0.02,
        "daily_change_rate": 0.1,
        "incremental_retention_days": 30,
        "weekly_full_retention": 4,
        "monthly_retention": 6,
        "annually_retention": 0,
        "incremental_retention_dr": 30,
        "incremental_retention_cloud": 0,
        "weekly_full_retention_dr": 4,
        "weekly_full_retention_cloud": 0,
        "monthly_full_retention_dr": 6,
        "monthly_full_retention_cloud": 0,
        "annually_full_retention_dr": 0,
        "annually_full_retention_cloud": 0,
        "initial_dedup_rate": 0.7,
        "dedup_rate": 0.9,
        "incremental_backup_level": "none",
        "log_backup_incremental_level": "none",
        "log_backup_capable": True,
        "log_backup_frequency_minutes": 2,
        "appliance_front_end_network": appliance.NetworkType.auto,
        "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
        "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
        "force_small_dup_jobs": 30,
        "appliance_dr_network": appliance.NetworkType.auto,
        "appliance_ltr_network": appliance.NetworkType.auto,
        "files": 1,
        "channels": 1,
        "files_per_channel": 1,
        "dedupe_rate_adl_full": 0.95,
        "incremental_per_week": 5,
        "full_backup_per_week": 1,
    }
    w3 = {
        "workload_name": "andrew_typing",
        "workload_type": "SQL",
        "number_of_clients": 1,
        "workload_size": utils.Size.assume_unit(5, "TB"),
        "storage_lifecycle_policy": "default",
        "workload_isolation": False,
        "universal_share": False,
        "domain": "Domain-1",
        "client_dedup": False,
        "region": "DC",
        "dr_dest": "SF",
        "backup_location_policy": "local+dr",
        "annual_growth_rate": 0.2,
        "daily_change_rate": 0.15,
        "incremental_retention_days": 15,  # retention_level_for_inc_backup_week (default 30 in use)
        "weekly_full_retention": 4,  # retention_level_for_week_full
        "monthly_retention": 6,  # retention_level_of_monthly_full_backup
        "annually_retention": 2,
        "incremental_retention_dr": 15,
        "incremental_retention_cloud": 0,
        "weekly_full_retention_dr": 4,
        "weekly_full_retention_cloud": 0,
        "monthly_full_retention_dr": 6,
        "monthly_full_retention_cloud": 0,
        "annually_full_retention_dr": 0,
        "annually_full_retention_cloud": 0,
        "initial_dedup_rate": 0.7,
        "dedup_rate": 0.75,
        "incremental_backup_level": "none",
        "log_backup_incremental_level": "none",
        "log_backup_capable": True,
        "log_backup_frequency_minutes": 2,  # .
        "appliance_front_end_network": appliance.NetworkType.auto,
        "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
        "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
        "force_small_dup_jobs": 30,
        "appliance_dr_network": appliance.NetworkType.auto,
        "appliance_ltr_network": appliance.NetworkType.auto,
        "files": 1,
        "channels": 1,
        "files_per_channel": 1,
        "dedupe_rate_adl_full": 0.85,
        "incremental_per_week": 5,
        "full_backup_per_week": 1,
    }
    return [w1, w2, w3]


@pytest.fixture
def test_zero_and_tiny_workloads():
    w1 = {
        "workload_name": "zero_workload_size",
        "workload_type": "File System",
        "workload_size": utils.Size.assume_unit(0.0, "TB"),
        "number_of_clients": 10,
        "storage_lifecycle_policy": "default",
        "workload_isolation": False,
        "universal_share": False,
        "domain": "Domain-X",
        "client_dedup": False,
        "region": "DC",
        "weekly_full_retention": 4,
        "monthly_retention": 6,
        "annually_retention": 0,
        "incremental_retention_dr": 0,
        "incremental_retention_cloud": 0,
        "weekly_full_retention_dr": 0,
        "weekly_full_retention_cloud": 0,
        "monthly_full_retention_dr": 0,
        "monthly_full_retention_cloud": 0,
        "annually_full_retention_dr": 0,
        "annually_full_retention_cloud": 0,
        "daily_change_rate": 0.05,
        "initial_dedup_rate": 0.75,
        "incremental_retention_days": 30,
        "incremental_backup_level": "differential",
        "log_backup_incremental_level": "differential",
        "log_backup_capable": False,
        "log_backup_frequency_minutes": 15,
        "dr_dest": None,
        "backup_location_policy": "local only",
        "annual_growth_rate": 0.2,
        "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
        "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
        "force_small_dup_jobs": 30,
        "files": 100000,
        "channels": 0,
        "files_per_channel": 1,
        "appliance_front_end_network": appliance.NetworkType.auto,
        "appliance_dr_network": appliance.NetworkType.auto,
        "appliance_ltr_network": appliance.NetworkType.auto,
        "dedupe_rate_adl_full": 0.95,
        "dedup_rate": 0.85,
        "incremental_per_week": 5,
        "full_backup_per_week": 1,
    }
    w2 = {
        "workload_name": "tiny_workload_size",
        "workload_type": "File System",
        "workload_size": utils.Size.assume_unit(0.0001, "TB"),
        "number_of_clients": 10,
        "storage_lifecycle_policy": "default",
        "workload_isolation": False,
        "universal_share": False,
        "domain": "Domain-X",
        "client_dedup": False,
        "region": "DC",
        "weekly_full_retention": 4,
        "monthly_retention": 6,
        "annually_retention": 0,
        "incremental_retention_dr": 0,
        "incremental_retention_cloud": 0,
        "weekly_full_retention_dr": 0,
        "weekly_full_retention_cloud": 0,
        "monthly_full_retention_dr": 0,
        "monthly_full_retention_cloud": 0,
        "annually_full_retention_dr": 0,
        "annually_full_retention_cloud": 0,
        "daily_change_rate": 0.05,
        "initial_dedup_rate": 0.75,
        "incremental_retention_days": 30,
        "incremental_backup_level": "differential",
        "log_backup_incremental_level": "differential",
        "log_backup_capable": False,
        "log_backup_frequency_minutes": 15,
        "dr_dest": None,
        "backup_location_policy": "local only",
        "annual_growth_rate": 0.2,
        "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
        "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
        "force_small_dup_jobs": 30,
        "files": 100000,
        "channels": 0,
        "files_per_channel": 1,
        "appliance_front_end_network": appliance.NetworkType.auto,
        "appliance_dr_network": appliance.NetworkType.auto,
        "appliance_ltr_network": appliance.NetworkType.auto,
        "dedupe_rate_adl_full": 0.95,
        "dedup_rate": 0.85,
        "incremental_per_week": 5,
        "full_backup_per_week": 1,
    }
    return [w1, w2]


@pytest.fixture
def test_workloads_dict():
    workload_sources = {
        "exp": {
            "workload_name": "exp",
            "workload_type": "File System",
            "workload_size": utils.Size.assume_unit(5, "TB"),
            "number_of_clients": 11,
            "storage_lifecycle_policy": "default",
            "workload_isolation": False,
            "universal_share": False,
            "domain": "Domain-1",
            "client_dedup": False,
            "region": "DC",
            "weekly_full_retention": 4,
            "monthly_retention": 4,
            "annually_retention": 0,
            "incremental_retention_dr": 0,
            "incremental_retention_cloud": 0,
            "weekly_full_retention_dr": 0,
            "weekly_full_retention_cloud": 0,
            "monthly_full_retention_dr": 0,
            "monthly_full_retention_cloud": 0,
            "annually_full_retention_dr": 0,
            "annually_full_retention_cloud": 0,
            "daily_change_rate": 0.2,
            "initial_dedup_rate": 0.8,
            "incremental_retention_days": 30,
            "incremental_backup_level": "differential",
            "log_backup_incremental_level": "differential",
            "log_backup_capable": False,
            "log_backup_frequency_minutes": None,
            "dr_dest": None,
            "backup_location_policy": "local only",
            "annual_growth_rate": 0.2,
            "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
            "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
            "force_small_dup_jobs": 30,
            "files": 1,
            "channels": 1,
            "files_per_channel": 1,
            "appliance_front_end_network": appliance.NetworkType.auto,
            "appliance_dr_network": appliance.NetworkType.auto,
            "appliance_ltr_network": appliance.NetworkType.auto,
            "dedupe_rate_adl_full": 0.95,
            "dedup_rate": 0.85,
            "incremental_per_week": 5,
            "full_backup_per_week": 1,
        },
        "exp_other_site": {
            "workload_name": "exp2",
            "workload_type": "File System",
            "workload_size": utils.Size.assume_unit(5, "TB"),
            "number_of_clients": 11,
            "storage_lifecycle_policy": "default",
            "workload_isolation": False,
            "universal_share": False,
            "domain": "Domain-1",
            "client_dedup": False,
            "region": "SF",
            "weekly_full_retention": 4,
            "monthly_retention": 4,
            "annually_retention": 0,
            "incremental_retention_dr": 0,
            "incremental_retention_cloud": 0,
            "weekly_full_retention_dr": 0,
            "weekly_full_retention_cloud": 0,
            "monthly_full_retention_dr": 0,
            "monthly_full_retention_cloud": 0,
            "annually_full_retention_dr": 0,
            "annually_full_retention_cloud": 0,
            "daily_change_rate": 0.2,
            "initial_dedup_rate": 0.8,
            "incremental_retention_days": 30,
            "log_backup_incremental_level": "differential",
            "incremental_backup_level": "differential",
            "log_backup_capable": False,
            "log_backup_frequency_minutes": None,
            "dr_dest": None,
            "backup_location_policy": "local only",
            "annual_growth_rate": 0.2,
            "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
            "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
            "force_small_dup_jobs": 30,
            "files": 1,
            "channels": 1,
            "files_per_channel": 1,
            "appliance_front_end_network": appliance.NetworkType.auto,
            "appliance_dr_network": appliance.NetworkType.auto,
            "appliance_ltr_network": appliance.NetworkType.auto,
            "dedupe_rate_adl_full": 0.95,
            "dedup_rate": 0.85,
            "incremental_per_week": 5,
            "full_backup_per_week": 1,
        },
        "exp2": {
            "workload_name": "exp2",
            "workload_type": "File System",
            "workload_size": utils.Size.assume_unit(1, "TB"),
            "number_of_clients": 5,
            "storage_lifecycle_policy": "default",
            "workload_isolation": False,
            "universal_share": False,
            "domain": "Domain-1",
            "client_dedup": False,
            "region": "DC",
            "weekly_full_retention": 4,
            "monthly_retention": 4,
            "annually_retention": 0,
            "incremental_retention_dr": 0,
            "incremental_retention_cloud": 0,
            "weekly_full_retention_dr": 0,
            "weekly_full_retention_cloud": 0,
            "monthly_full_retention_dr": 0,
            "monthly_full_retention_cloud": 0,
            "annually_full_retention_dr": 0,
            "annually_full_retention_cloud": 0,
            "daily_change_rate": 0,
            "initial_dedup_rate": 0.8,
            "incremental_retention_days": 30,
            "incremental_backup_level": "differential",
            "log_backup_incremental_level": "differential",
            "log_backup_capable": False,
            "log_backup_frequency_minutes": None,
            "dr_dest": None,
            "backup_location_policy": "local only",
            "annual_growth_rate": 0,
            "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
            "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
            "force_small_dup_jobs": 30,
            "files": 1,
            "channels": 1,
            "files_per_channel": 1,
            "appliance_front_end_network": appliance.NetworkType.auto,
            "appliance_dr_network": appliance.NetworkType.auto,
            "appliance_ltr_network": appliance.NetworkType.auto,
            "dedupe_rate_adl_full": 0.95,
            "dedup_rate": 0.85,
            "incremental_per_week": 5,
            "full_backup_per_week": 1,
        },
        "dr_workload": {
            "workload_name": "exp",
            "workload_type": "File System",
            "workload_size": utils.Size.assume_unit(5, "TB"),
            "storage_lifecycle_policy": "default",
            "workload_isolation": False,
            "universal_share": False,
            "number_of_clients": 11,
            "domain": "Domain-1",
            "client_dedup": False,
            "region": "DC",
            "weekly_full_retention": 4,
            "monthly_retention": 4,
            "annually_retention": 0,
            "incremental_retention_dr": 30,
            "incremental_retention_cloud": 0,
            "weekly_full_retention_dr": 4,
            "weekly_full_retention_cloud": 0,
            "monthly_full_retention_dr": 4,
            "monthly_full_retention_cloud": 0,
            "annually_full_retention_dr": 0,
            "annually_full_retention_cloud": 0,
            "daily_change_rate": 0.2,
            "initial_dedup_rate": 0.8,
            "incremental_retention_days": 30,
            "incremental_backup_level": "differential",
            "log_backup_incremental_level": "differential",
            "log_backup_capable": False,
            "log_backup_frequency_minutes": None,
            "dr_dest": "SF",
            "backup_location_policy": "local+dr",
            "annual_growth_rate": 0.2,
            "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
            "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
            "force_small_dup_jobs": 30,
            "files": 1,
            "channels": 1,
            "files_per_channel": 1,
            "appliance_front_end_network": appliance.NetworkType.auto,
            "appliance_dr_network": appliance.NetworkType.auto,
            "appliance_ltr_network": appliance.NetworkType.auto,
            "dedupe_rate_adl_full": 0.95,
            "dedup_rate": 0.85,
            "incremental_per_week": 5,
            "full_backup_per_week": 1,
        },
        "db_workload": {
            "workload_name": "db_workload",
            "workload_type": "Oracle",
            "workload_size": utils.Size.assume_unit(5, "GB"),
            "storage_lifecycle_policy": "default",
            "workload_isolation": False,
            "universal_share": False,
            "number_of_clients": 10,
            "domain": "Domain-1",
            "client_dedup": True,
            "region": "DC",
            "weekly_full_retention": 4,
            "monthly_retention": 4,
            "annually_retention": 0,
            "incremental_retention_dr": 0,
            "incremental_retention_cloud": 0,
            "weekly_full_retention_dr": 0,
            "weekly_full_retention_cloud": 0,
            "monthly_full_retention_dr": 0,
            "monthly_full_retention_cloud": 0,
            "annually_full_retention_dr": 0,
            "annually_full_retention_cloud": 0,
            "daily_change_rate": 0.2,
            "initial_dedup_rate": 0.8,
            "incremental_retention_days": 30,
            "incremental_backup_level": "differential",
            "log_backup_incremental_level": "differential",
            "log_backup_capable": True,
            "log_backup_frequency_minutes": 15,
            "dr_dest": None,
            "backup_location_policy": "local only",
            "annual_growth_rate": 0.2,
            "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
            "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
            "force_small_dup_jobs": 30,
            "files": 1,
            "channels": 1,
            "files_per_channel": 1,
            "appliance_front_end_network": appliance.NetworkType.auto,
            "appliance_dr_network": appliance.NetworkType.auto,
            "appliance_ltr_network": appliance.NetworkType.auto,
            "dedupe_rate_adl_full": 0.95,
            "dedup_rate": 0.85,
            "incremental_per_week": 5,
            "full_backup_per_week": 1,
        },
        "vm_workload": {
            "workload_name": "vm_workload",
            "workload_type": "VMware",
            "workload_size": utils.Size.assume_unit(1, "GB"),
            "number_of_clients": 500,
            "storage_lifecycle_policy": "default",
            "workload_isolation": False,
            "universal_share": False,
            "domain": "Domain-1",
            "client_dedup": False,
            "region": "DC",
            "weekly_full_retention": 4,
            "monthly_retention": 4,
            "annually_retention": 0,
            "incremental_retention_dr": 0,
            "incremental_retention_cloud": 0,
            "weekly_full_retention_dr": 0,
            "weekly_full_retention_cloud": 0,
            "monthly_full_retention_dr": 0,
            "monthly_full_retention_cloud": 0,
            "annually_full_retention_dr": 0,
            "annually_full_retention_cloud": 0,
            "daily_change_rate": 0.2,
            "initial_dedup_rate": 0.8,
            "incremental_retention_days": 30,
            "incremental_backup_level": "none",
            "log_backup_incremental_level": "none",
            "log_backup_capable": False,
            "log_backup_frequency_minutes": None,
            "dr_dest": None,
            "backup_location_policy": "local only",
            "annual_growth_rate": 0.2,
            "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
            "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
            "force_small_dup_jobs": 30,
            "files": 1,
            "channels": 1,
            "files_per_channel": 1,
            "appliance_front_end_network": appliance.NetworkType.auto,
            "appliance_dr_network": appliance.NetworkType.auto,
            "appliance_ltr_network": appliance.NetworkType.auto,
            "dedupe_rate_adl_full": 0.95,
            "dedup_rate": 0.85,
            "incremental_per_week": 0,
            "full_backup_per_week": 1,
        },
        "dr_ltr_workload": {
            "workload_name": "exp",
            "workload_type": "File System",
            "workload_size": utils.Size.assume_unit(5, "TB"),
            "number_of_clients": 11,
            "storage_lifecycle_policy": "default",
            "workload_isolation": False,
            "universal_share": False,
            "domain": "Domain-1",
            "client_dedup": False,
            "region": "DC",
            "weekly_full_retention": 4,
            "monthly_retention": 4,
            "annually_retention": 0,
            "incremental_retention_days": 30,
            "incremental_retention_dr": 30,
            "weekly_full_retention_dr": 4,
            "monthly_full_retention_dr": 4,
            "incremental_retention_cloud": 0,
            "weekly_full_retention_cloud": 4,
            "monthly_full_retention_cloud": 4,
            "annually_full_retention_dr": 0,
            "annually_full_retention_cloud": 0,
            "daily_change_rate": 0.2,
            "initial_dedup_rate": 0.8,
            "incremental_backup_level": "differential",
            "log_backup_incremental_level": "differential",
            "log_backup_capable": False,
            "log_backup_frequency_minutes": None,
            "dr_dest": "SF",
            "backup_location_policy": "local+dr+ltr",
            "annual_growth_rate": 0.2,
            "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
            "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
            "force_small_dup_jobs": 30,
            "files": 1,
            "channels": 1,
            "files_per_channel": 1,
            "appliance_front_end_network": appliance.NetworkType.auto,
            "appliance_dr_network": appliance.NetworkType.auto,
            "appliance_ltr_network": appliance.NetworkType.auto,
            "dedupe_rate_adl_full": 0.95,
            "dedup_rate": 0.85,
            "incremental_per_week": 5,
            "full_backup_per_week": 1,
        },
        "files_backup": {
            "workload_name": "files_backup",
            "workload_type": "File System",
            "workload_size": utils.Size.assume_unit(5, "TB"),
            "number_of_clients": 11,
            "storage_lifecycle_policy": "default",
            "workload_isolation": False,
            "universal_share": False,
            "region": "DC",
            "domain": "Domain-1",
            "client_dedup": False,
            "weekly_full_retention": 4,
            "monthly_retention": 4,
            "annually_retention": 0,
            "incremental_retention_dr": 0,
            "incremental_retention_cloud": 0,
            "weekly_full_retention_dr": 0,
            "weekly_full_retention_cloud": 0,
            "monthly_full_retention_dr": 0,
            "monthly_full_retention_cloud": 0,
            "annually_full_retention_dr": 0,
            "annually_full_retention_cloud": 0,
            "daily_change_rate": 0.2,
            "initial_dedup_rate": 0.8,
            "incremental_retention_days": 30,
            "incremental_backup_level": "differential",
            "log_backup_incremental_level": "differential",
            "log_backup_capable": False,
            "log_backup_frequency_minutes": None,
            "dr_dest": None,
            "backup_location_policy": "local only",
            "annual_growth_rate": 0.2,
            "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
            "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
            "force_small_dup_jobs": 30,
            "files": 1_000_000,
            "channels": 0,
            "files_per_channel": 1,
            "appliance_front_end_network": appliance.NetworkType.auto,
            "appliance_dr_network": appliance.NetworkType.auto,
            "appliance_ltr_network": appliance.NetworkType.auto,
            "dedupe_rate_adl_full": 0.95,
            "dedup_rate": 0.85,
            "incremental_per_week": 5,
            "full_backup_per_week": 1,
        },
    }
    workloads = {}
    for wname, wspec in workload_sources.items():
        w = workload.Workload(wspec)
        w.calculate_capacity(
            utils.DEFAULT_TIMEFRAME, utils.DEFAULT_WORST_CASE_CLOUD_FACTOR
        )
        workloads[wname] = w
    return workloads


@pytest.fixture
def test_slp():
    slp1 = {
        "storage_lifecycle_policy": "default",
        "region": "DC",
        "dr_dest": "SF",
        "domain": "Domain-1",
        "backup_location_policy": "local+dr",
        "incremental_retention_days": 30,
        "weekly_full_retention": 4,
        "monthly_retention": 6,
        "annually_retention": 0,
        "incremental_retention_dr": 30,
        "incremental_retention_cloud": 0,
        "weekly_full_retention_dr": 4,
        "weekly_full_retention_cloud": 0,
        "monthly_full_retention_dr": 6,
        "monthly_full_retention_cloud": 0,
        "annually_full_retention_dr": 0,
        "annually_full_retention_cloud": 0,
        "incremental_backup_level": "differential",
        "log_backup_incremental_level": "differential",
        "log_backup_frequency_minutes": 15,
        "appliance_front_end_network": appliance.NetworkType.auto,
        "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
        "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
        "force_small_dup_jobs": 30,
        "appliance_dr_network": appliance.NetworkType.auto,
        "appliance_ltr_network": appliance.NetworkType.auto,
        "incremental_per_week": 5,
        "full_backup_per_week": 1,
    }
    slp2 = {
        "storage_lifecycle_policy": "cloud-catalyst",
        "region": "DC",
        "dr_dest": "SF",
        "domain": None,
        "backup_location_policy": "local+dr",
        "incremental_retention_days": 30,
        "weekly_full_retention": 4,
        "monthly_retention": 6,
        "annually_retention": 0,
        "incremental_retention_dr": 30,
        "incremental_retention_cloud": 0,
        "weekly_full_retention_dr": 4,
        "weekly_full_retention_cloud": 0,
        "monthly_full_retention_dr": 6,
        "monthly_full_retention_cloud": 0,
        "annually_full_retention_dr": 0,
        "annually_full_retention_cloud": 0,
        "incremental_backup_level": "none",
        "log_backup_incremental_level": "none",
        "log_backup_frequency_minutes": 2,
        "appliance_front_end_network": appliance.NetworkType.auto,
        "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
        "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
        "force_small_dup_jobs": 30,
        "appliance_dr_network": appliance.NetworkType.auto,
        "appliance_ltr_network": appliance.NetworkType.auto,
        "incremental_per_week": 5,
        "full_backup_per_week": 1,
    }
    slp3 = {
        "storage_lifecycle_policy": "slp_new",
        "region": "DC",
        "dr_dest": "SF",
        "domain": "",
        "backup_location_policy": "local+dr",
        "incremental_retention_days": 15,  # retention_level_for_inc_backup_week (default 30 in use)
        "weekly_full_retention": 4,  # retention_level_for_week_full
        "monthly_retention": 6,  # retention_level_of_monthly_full_backup
        "annually_retention": 2,
        "incremental_retention_dr": 15,
        "incremental_retention_cloud": 0,
        "weekly_full_retention_dr": 4,
        "weekly_full_retention_cloud": 0,
        "monthly_full_retention_dr": 6,
        "monthly_full_retention_cloud": 0,
        "annually_full_retention_dr": 0,
        "annually_full_retention_cloud": 0,
        "incremental_backup_level": "none",
        "log_backup_incremental_level": "none",
        "log_backup_frequency_minutes": 2,  # .
        "appliance_front_end_network": appliance.NetworkType.auto,
        "min_size_dup_jobs": utils.Size.assume_unit(8, "GB"),
        "max_size_dup_jobs": utils.Size.assume_unit(100, "GB"),
        "force_small_dup_jobs": 30,
        "appliance_dr_network": appliance.NetworkType.auto,
        "appliance_ltr_network": appliance.NetworkType.auto,
        "incremental_per_week": 5,
        "full_backup_per_week": 1,
    }
    return [slp1, slp2, slp3]


@pytest.fixture
def test_per_appliance_safety_margins():
    pasm = {
        "5150": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.7,
            "CPU": 0.7,
            "NW": 0.8,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 1000,
            "DBs@15": 5,
            "VMs": 100,
            "Streams": 8,
            "Version": "Latest",
            "Max_Cal_Cap": None,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 2,
            "LUN_Size": None,
        },
        "5240": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.7,
            "CPU": 0.7,
            "NW": 0.8,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 1000,
            "DBs@15": 5,
            "VMs": 100,
            "Streams": 8,
            "Version": "Latest",
            "Max_Cal_Cap": None,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 6,
            "LUN_Size": None,
        },
        "5250": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.7,
            "CPU": 0.7,
            "NW": 0.8,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 1000,
            "DBs@15": 5,
            "VMs": 100,
            "Streams": 8,
            "Version": "Latest",
            "Max_Cal_Cap": None,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 7,
            "LUN_Size": None,
        },
        "5250-FLEX": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.8,
            "CPU": 0.7,
            "NW": 0.7,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 25000,
            "DBs@15": None,
            "VMs": 7500,
            "Streams": 350,
            "Version": "Latest",
            "Max_Cal_Cap": None,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 12,
            "LUN_Size": 65.5,
        },
        "5340": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.7,
            "CPU": 0.7,
            "NW": 0.8,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 1000,
            "DBs@15": 5,
            "VMs": 100,
            "Streams": 8,
            "Version": "Latest",
            "Max_Cal_Cap": 960,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 480,
            "LUN_Size": None,
        },
        "5340-FLEX": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.8,
            "CPU": 0.7,
            "NW": 0.7,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 25000,
            "DBs@15": None,
            "VMs": 7500,
            "Streams": 350,
            "Version": "Latest",
            "Max_Cal_Cap": 960,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 5,
            "LUN_Size": 80,
        },
        "5340-HA": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.7,
            "CPU": 0.7,
            "NW": 0.8,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 1000,
            "DBs@15": 5,
            "VMs": 100,
            "Streams": 8,
            "Version": "Latest",
            "Max_Cal_Cap": 960,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 960,
            "LUN_Size": None,
        },
        "5340-HA-FLEX": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.8,
            "CPU": 0.7,
            "NW": 0.7,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 25000,
            "DBs@15": None,
            "VMs": 7500,
            "Streams": 350,
            "Version": "Latest",
            "Max_Cal_Cap": 960,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 5,
            "LUN_Size": 80,
        },
        "5350": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.7,
            "CPU": 0.7,
            "NW": 0.8,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 1000,
            "DBs@15": 5,
            "VMs": 100,
            "Streams": 8,
            "Version": "Latest",
            "Max_Cal_Cap": 960,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 480,
            "LUN_Size": None,
        },
        "5350-FLEX": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.8,
            "CPU": 0.7,
            "NW": 0.7,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 25000,
            "DBs@15": None,
            "VMs": 7500,
            "Streams": 350,
            "Version": "Latest",
            "Max_Cal_Cap": 960,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 5,
            "LUN_Size": 80,
        },
        "5350-HA-FLEX": {
            "Horizon": 3,
            "Extension": 5,
            "Capacity": 0.8,
            "CPU": 0.7,
            "NW": 0.7,
            "IO": 0.7,
            "Memory": 0.7,
            "Jobs_Per_Day": 25000,
            "DBs@15": None,
            "VMs": 7500,
            "Streams": 350,
            "Version": "Latest",
            "Max_Cal_Cap": 960,
            "Files": None,
            "Images": None,
            "Max_Catalog_Size": 5,
            "LUN_Size": 80,
        },
        "Access 3340": {
            "Capacity": 0.8,
            "CPU": 0.7,
        },
    }
    return pasm


@pytest.fixture
def use_tempdir():
    tdir = tempfile.gettempdir()
    yield tdir
