# VERITAS: Copyright (c) 2022 Veritas Technologies LLC. All rights reserved.
#
# THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF VERITAS
# TECHNOLOGIES LLC.  USE, DISCLOSURE OR REPRODUCTION IS PROHIBITED WITHOUT THE
# PRIOR EXPRESS WRITTEN PERMISSION OF VERITAS TECHNOLOGIES LLC.
#
# The Licensed Software and Documentation are deemed to be commercial computer
# software as defined in FAR 12.212 and subject to restricted rights as defined
# in FAR Section 52.227-19 "Commercial Computer Software - Restricted Rights"
# and DFARS 227.7202, Rights in "Commercial Computer Software or Commercial
# Computer Software Documentation," as applicable, and any successor
# regulations, whether delivered by Veritas as on premises or hosted services.
# Any use, modification, reproduction release, performance, display or
# disclosure of the Licensed Software and Documentation by the U.S. Government
# shall be solely in accordance with the terms of this Agreement.
# Product version __version__

import pytest


@pytest.fixture
def test_appliances():
    a1 = {
        "name": "5150 32TB_Capacity 0_Shelves 64_RAM  4x1GbE 2x10GbE_Copper",
        "model": "5150",
        "shelves": "0",
        "shelf_size": {"value": "0", "unit": "TB"},
        "capacity": {"value": "32", "unit": "TB"},
        "shelf_capacity": {"value": "0", "unit": "TB"},
        "calculated_capacity": {"value": "32", "unit": "TB"},
        "number_of_appliance_drives": "4",
        "drives_per_shelf": "0",
        "number_of_shelf_drives": "0",
        "number_of_total_drives": "4",
        "number_of_calculated_drives": "4",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "64", "unit": "GB"},
        "io_config": "C",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "2", "io": "1600"},
        "ten_gbe_sfp": {"count": "0", "io": "0"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    a2 = {
        "name": "5150 32TB_Capacity 0_Shelves 64_RAM  4x1GbE 2x10GbE_SFP",
        "model": "5150",
        "shelves": "0",
        "shelf_size": {"value": "0", "unit": "TB"},
        "capacity": {"value": "32", "unit": "TB"},
        "shelf_capacity": {"value": "0", "unit": "TB"},
        "calculated_capacity": {"value": "32", "unit": "TB"},
        "number_of_appliance_drives": "4",
        "drives_per_shelf": "0",
        "number_of_shelf_drives": "0",
        "number_of_total_drives": "4",
        "number_of_calculated_drives": "4",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "64", "unit": "GB"},
        "io_config": "D",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "2", "io": "1600"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    a3 = {
        "name": "5340 960TB_Capacity 4_Shelves 1536_RAM  4x1GbE 8x10GbE_SFP 2x16Gb_FC",
        "model": "5340",
        "shelves": "4",
        "shelf_size": {"value": "240", "unit": "TB"},
        "capacity": {"value": "960", "unit": "TB"},
        "shelf_capacity": {"value": "960", "unit": "TB"},
        "calculated_capacity": {"value": "960", "unit": "TB"},
        "number_of_appliance_drives": "0",
        "drives_per_shelf": "84",
        "number_of_shelf_drives": "336",
        "number_of_total_drives": "336",
        "number_of_calculated_drives": "336",
        "drive_size": {"value": "4", "unit": "TB"},
        "memory": {"value": "1536", "unit": "GB"},
        "io_config": "F",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "8", "io": "6400"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "2", "io": "2100"},
    }
    a4 = {
        "name": "5340 1920TB_Capacity 4_Shelves 1536_RAM  4x1GbE 8x10GbE_SFP 2x16Gb_FC",
        "model": "5340",
        "shelves": "4",
        "shelf_size": {"value": "480", "unit": "TB"},
        "capacity": {"value": "1920", "unit": "TB"},
        "shelf_capacity": {"value": "1920", "unit": "TB"},
        "calculated_capacity": {"value": "1920", "unit": "TB"},
        "number_of_appliance_drives": "0",
        "drives_per_shelf": "84",
        "number_of_shelf_drives": "336",
        "number_of_total_drives": "336",
        "number_of_calculated_drives": "336",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "1536", "unit": "GB"},
        "io_config": "F",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "8", "io": "6400"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "2", "io": "2100"},
    }
    a5 = {
        "name": "5250 400GB_Capacity 0_Shelves 64_RAM  4x1GbE 2x10GbE_SFP",
        "model": "5250",
        "shelves": "0",
        "shelf_size": {"value": "65.5", "unit": "TB"},
        "capacity": {"value": "400", "unit": "GB"},
        "shelf_capacity": {"value": "0", "unit": "TB"},
        "calculated_capacity": {"value": "400", "unit": "GB"},
        "number_of_appliance_drives": "8",
        "drives_per_shelf": "12",
        "number_of_shelf_drives": "0",
        "number_of_total_drives": "8",
        "number_of_calculated_drives": "8",
        "drive_size": {"value": "2", "unit": "TB"},
        "memory": {"value": "64", "unit": "GB"},
        "io_config": "A",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "2", "io": "1600"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    a6 = {
        "name": "5250 402TB_Capacity 6_Shelves 512_RAM  4x1GbE 6x10GbE_Copper 4x16Gb_FC",
        "model": "5250",
        "shelves": "6",
        "shelf_size": {"value": "65.5", "unit": "TB"},
        "capacity": {"value": "402", "unit": "TB"},
        "shelf_capacity": {"value": "393", "unit": "TB"},
        "calculated_capacity": {"value": "393", "unit": "TB"},
        "number_of_appliance_drives": "8",
        "drives_per_shelf": "12",
        "number_of_shelf_drives": "72",
        "number_of_total_drives": "80",
        "number_of_calculated_drives": "72",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "512", "unit": "GB"},
        "io_config": "F",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "6", "io": "4800"},
        "ten_gbe_sfp": {"count": "0", "io": "0"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "4", "io": "4200"},
    }
    a7 = {
        "name": "5340-FLEX 1920TB_Capacity 4_Shelves 1536_RAM  4x1GbE 4x10GbE_SFP 6x16Gb_FC",
        "model": "5340-FLEX",
        "shelves": "4",
        "shelf_size": {"value": "480", "unit": "TB"},
        "capacity": {"value": "1920", "unit": "TB"},
        "shelf_capacity": {"value": "1920", "unit": "TB"},
        "calculated_capacity": {"value": "1920", "unit": "TB"},
        "number_of_appliance_drives": "0",
        "drives_per_shelf": "84",
        "number_of_shelf_drives": "336",
        "number_of_total_drives": "336",
        "number_of_calculated_drives": "336",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "1536", "unit": "GB"},
        "io_config": "H",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "4", "io": "3200"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "6", "io": "6300"},
    }
    a8 = {
        "name": "5250 74.5TB_Capacity 1_Shelves 256_RAM  4x1GbE 2x10GbE_SFP",
        "model": "5250",
        "shelves": "1",
        "shelf_size": {"value": "65.5", "unit": "TB"},
        "capacity": {"value": "74.5", "unit": "TB"},
        "shelf_capacity": {"value": "65.5", "unit": "TB"},
        "calculated_capacity": {"value": "65.5", "unit": "TB"},
        "number_of_appliance_drives": "7",
        "drives_per_shelf": "11",
        "number_of_shelf_drives": "11",
        "number_of_total_drives": "18",
        "number_of_calculated_drives": "11",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "256", "unit": "GB"},
        "io_config": "A",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "2", "io": "1600"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    a9 = {
        "name": "5250-FLEX 74.5TB_Capacity 1_Shelves 256_RAM  4x1GbE 2x10GbE_SFP",
        "model": "5250-FLEX",
        "shelves": "1",
        "shelf_size": {"value": "65.5", "unit": "TB"},
        "capacity": {"value": "74.5", "unit": "TB"},
        "shelf_capacity": {"value": "65.5", "unit": "TB"},
        "calculated_capacity": {"value": "65.5", "unit": "TB"},
        "number_of_appliance_drives": "7",
        "drives_per_shelf": "11",
        "number_of_shelf_drives": "11",
        "number_of_total_drives": "18",
        "number_of_calculated_drives": "11",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "256", "unit": "GB"},
        "io_config": "A",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "2", "io": "1600"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    a10 = {
        "name": "5150 15TB_Capacity 0_Shelves 64_RAM  4x1GbE 2x10GbE_SFP",
        "model": "5150",
        "shelves": "0",
        "shelf_size": {"value": "0", "unit": "TB"},
        "capacity": {"value": "15", "unit": "TB"},
        "shelf_capacity": {"value": "0", "unit": "TB"},
        "calculated_capacity": {"value": "15", "unit": "TB"},
        "number_of_appliance_drives": "4",
        "drives_per_shelf": "0",
        "number_of_shelf_drives": "0",
        "number_of_total_drives": "4",
        "number_of_calculated_drives": "4",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "64", "unit": "GB"},
        "io_config": "D",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "2", "io": "1600"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }

    return [a1, a2, a3, a4, a5, a6, a7, a8, a9, a10]


@pytest.fixture
def test_appliances_with_non_5150():
    a1 = {
        "name": "5340-HA 120TB_Capacity 0.5_Shelves 768_RAM  4x1GbE 16x10GbE_SFP 4x8Gb_FC",
        "model": "5340-HA",
        "shelves": "0",
        "shelf_size": {"value": "49", "unit": "TB"},
        "capacity": {"value": "4", "unit": "TB"},
        "shelf_capacity": {"value": "0", "unit": "TB"},
        "calculated_capacity": {"value": "4", "unit": "TB"},
        "number_of_appliance_drives": "7",
        "drives_per_shelf": "12",
        "number_of_shelf_drives": "0",
        "number_of_total_drives": "7",
        "number_of_calculated_drives": "7",
        "drive_size": {"value": "1", "unit": "TB"},
        "memory": {"value": "64", "unit": "GB"},
        "io_config": "A",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "2", "io": "1600"},
        "ten_gbe_sfp": {"count": "0", "io": "0"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    a2 = {
        "name": "5240 4TB_Capacity 0_Shelves 64_RAM  4x1GbE 2x10GbE_Copper 2x8Gb_FC",
        "model": "5240",
        "shelves": "0",
        "shelf_size": {"value": "49", "unit": "TB"},
        "capacity": {"value": "4", "unit": "TB"},
        "shelf_capacity": {"value": "0", "unit": "TB"},
        "calculated_capacity": {"value": "4", "unit": "TB"},
        "number_of_appliance_drives": "7",
        "drives_per_shelf": "12",
        "number_of_shelf_drives": "0",
        "number_of_total_drives": "7",
        "number_of_calculated_drives": "7",
        "drive_size": {"value": "1", "unit": "TB"},
        "memory": {"value": "64", "unit": "GB"},
        "io_config": "B",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "2", "io": "1600"},
        "ten_gbe_sfp": {"count": "0", "io": "0"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "2", "io": "1050"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    return [a1, a2]


@pytest.fixture
def test_appliance_safety():
    appl_config = {
        "name": "5150 32TB_Capacity 0_Shelves 64_RAM  4x1GbE 2x10GbE_SFP",
        "model": "5150",
        "shelves": "0",
        "shelf_size": {"value": "0", "unit": "TB"},
        "capacity": {"value": "32", "unit": "TB"},
        "shelf_capacity": {"value": "0", "unit": "TB"},
        "calculated_capacity": {"value": "32", "unit": "TB"},
        "number_of_appliance_drives": "4",
        "drives_per_shelf": "0",
        "number_of_shelf_drives": "0",
        "number_of_total_drives": "4",
        "number_of_calculated_drives": "4",
        "drive_size": {"value": "8", "unit": "TB"},
        "memory": {"value": "64", "unit": "GB"},
        "io_config": "D",
        "one_gbe": {"count": "4", "io": "320"},
        "ten_gbe_copper": {"count": "0", "io": "0"},
        "ten_gbe_sfp": {"count": "2", "io": "1600"},
        "twentyfive_gbe_sfp": {"count": "0", "io": "0"},
        "eight_gbfc": {"count": "0", "io": "0"},
        "sixteen_gbfc": {"count": "0", "io": "0"},
    }
    return appl_config
